### ISSUE TITLE
[Python3.8] ModuleNotFoundError: No module named 'thread'

### ISSUE THREAD

**Issue by augustozanellato** [kylef/irctk#2]
Can't install the library using python 3.8 because pip fails with
```
Collecting irctk
  Downloading IrcTK-0.2.7.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dwvnld14/irctk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dwvnld14/irctk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dwvnld14/irctk/pip-egg-info
         cwd: /tmp/pip-install-dwvnld14/irctk/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dwvnld14/irctk/setup.py", line 8, in <module>
        import irctk
      File "/tmp/pip-install-dwvnld14/irctk/irctk/__init__.py", line 9, in <module>
        from irctk.bot import Bot
      File "/tmp/pip-install-dwvnld14/irctk/irctk/bot.py", line 13, in <module>
        import thread
    ModuleNotFoundError: No module named 'thread'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kylef** [comment]
Hi @augustozanellato, I think you've sent your request to the wrong place. The "irctk" library on pypi is at https://github.com/maxcountryman/irctk.
