### ISSUE TITLE
Example script does not run

### ISSUE THREAD

**Issue by webquest-nz** [kylef/irctk#4]
```
 $ python3 example_irc_bot.py 
Task exception was never retrieved
future: <Task finished coro=<Bot.connect() done, defined at example_irc_bot.py:8> exception=AttributeError("'Channel' object has no attribute 'join'",)>
Traceback (most recent call last):
  File "example_irc_bot.py", line 11, in connect
    await client.connect(hostname, port, secure)
  File "/home/glenn/projects/logos-v2/irctk/irctk/client.py", line 85, in connect
    await self.connected()
  File "/home/glenn/projects/logos-v2/irctk/irctk/client.py", line 112, in connected
    self.process_message(message)
  File "/home/glenn/projects/logos-v2/irctk/irctk/client.py", line 374, in process_message
    func(message)
  File "/home/glenn/projects/logos-v2/irctk/irctk/client.py", line 398, in process_001
    self.irc_registered()
  File "/home/glenn/projects/logos-v2/irctk/irctk/client.py", line 656, in irc_registered
    module.irc_registered(self)
  File "/home/glenn/projects/logos-v2/irctk/irctk/client.py", line 714, in irc_registered
    self.delegate.irc_registered(client)
  File "example_irc_bot.py", line 15, in irc_registered
    channel.join()
AttributeError: 'Channel' object has no attribute 'join'
```

**Comment by kylef** [comment]
You're right, the interface of irctk changed over the years and the example has been neglected. That should be resolved now.
